import React, { useState, useEffect, useRef } from 'react';
import { useNavigate, Link, useLocation } from 'react-router-dom';
import { Sparkles, ArrowLeft, Send, Loader2, Wand2, PartyPopper, Heart, Calendar, AlertCircle } from 'lucide-react';
import { GoogleGenerativeAI } from "@google/generative-ai";
import { getAiConfig, createDesignFromAi } from '../utils/storage';

const SUGGESTIONS = [
    { icon: <Heart className="text-pink-500" />, label: "Elegant Wedding Invitation", prompt: "Create an elegant wedding invitation with floral watercolor borders and gold serif typography." },
    { icon: <PartyPopper className="text-orange-500" />, label: "Birthday Party Invite", prompt: "A fun and vibrant birthday party invitation for a 5-year-old with space and rocket theme." },
    { icon: <Calendar className="text-blue-500" />, label: "Corporate Event", prompt: "A professional and modern corporate event invitation with minimalist design and blue accents." },
    { icon: <Wand2 className="text-purple-500" />, label: "Magical Celebration", prompt: "A magical themed party invitation with glitter effects and whimsical purple-to-blue gradients." }
];

const AiGenerator = () => {
    const [prompt, setPrompt] = useState('');
    const [isGenerating, setIsGenerating] = useState(false);
    const [statusText, setStatusText] = useState('');
    const [selectedModel, setSelectedModel] = useState('gemini-1.5-flash');
    const [availableModels, setAvailableModels] = useState([]);
    
    const navigate = useNavigate();
    const location = useLocation();
    const inputRef = useRef(null);
    const hasAutoGenerated = useRef(false);

    useEffect(() => {
        const config = getAiConfig();
        if (config.model) {
            setSelectedModel(config.model);
        }
        if (config.apiKey) {
            fetchModels(config.apiKey);
        }
        
        // Handle URL prompt
        const params = new URLSearchParams(location.search);
        const urlPrompt = params.get('prompt');
        
        if (urlPrompt && !hasAutoGenerated.current) {
            setPrompt(urlPrompt);
            if (config.apiKey) {
                hasAutoGenerated.current = true;
                handleGenerate(urlPrompt);
            }
        } else if (inputRef.current) {
            inputRef.current.focus();
        }
    }, [location.search]);

    const fetchModels = async (apiKey) => {
        try {
            const res = await fetch(`https://generativelanguage.googleapis.com/v1/models?key=${apiKey}`);
            const data = await res.json();
            if (data.models) {
                const models = data.models
                    .filter(m => m.supportedGenerationMethods.includes('generateContent'))
                    .map(m => ({
                        id: m.name.replace('models/', ''),
                        name: m.displayName || m.name.split('/').pop()
                    }))
                    .sort((a,b) => b.id.localeCompare(a.id)); 
                
                if (models.length > 0) {
                    setAvailableModels(models);
                }
            }
        } catch (error) {
            console.error('Failed to fetch Gemini models:', error);
        }
    };

    const handleGenerate = async (finalPrompt = prompt) => {
        if (!finalPrompt.trim()) return;

        const config = getAiConfig();
        if (!config.apiKey) {
            alert("Please set your Gemini API Key in the Dashboard settings first.");
            navigate('/dashboard');
            return;
        }

        setIsGenerating(true);
        setStatusText("Analyzing your design requirements...");

        try {
            const genAI = new GoogleGenerativeAI(config.apiKey);
            const model = genAI.getGenerativeModel({ model: selectedModel });

            setStatusText("Sketching the layout structure...");
            
            const systemPrompt = `
                You are a world-class invitation and graphic designer. 
                Your goal is to generate a beautiful, responsive, and production-ready invitation design based on the user's request.

                Return ONLY a JSON object with this structure:
                {
                  "name": "A catchy name for the design",
                  "html": "The HTML content (must include a .invitation-container div)",
                  "css": "The CSS styles (scoped to the invitation container where possible)"
                }

                Design Constraints:
                - Use Google Fonts via @import if needed (e.g., Playfair Display, Montserrat).
                - Use modern CSS features (gradients, flexbox, grid, glassmorphism).
                - Ensure the layout is responsive and looks premium.
                - Maximize visual impact with background images (use high-quality Unsplash URLs if relevant).
                - The .invitation-container should be the main wrapper.
                - Avoid complex JS; focus on pure HTML/CSS.
                - The design should be suitable for a vertical 9:16 aspect ratio (approx 1080x1920).
            `;

            const fullPrompt = `System: ${systemPrompt}\n\nUser Request: ${finalPrompt}`;

            const result = await model.generateContent(fullPrompt);
            const response = await result.response;
            const text = response.text();
            
            setStatusText("Finalizing colors and typography...");
            
            // Extract JSON from the response
            const jsonMatch = text.match(/\{[\s\S]*\}/);
            if (!jsonMatch) throw new Error("Failed to parse AI response into valid design data.");
            
            const designData = JSON.parse(jsonMatch[0]);
            
            // Save and navigate
            const newDesign = createDesignFromAi(
                designData.name,
                designData.html,
                designData.css
            );

            setStatusText("Design ready! Opening editor...");
            setTimeout(() => {
                navigate(`/editor/${newDesign.id}`);
            }, 1000);

        } catch (error) {
            console.error("AI Generation failed:", error);
            alert(`AI Generation failed: ${error.message || 'Unknown error'}. Try selecting a different model.`);
            setIsGenerating(false);
            setStatusText("");
        }
    };

    return (
        <div className="min-h-screen bg-slate-50 flex flex-col font-sans">
            {/* Header */}
            <header className="px-6 py-4 flex justify-between items-center bg-white/50 backdrop-blur-md border-b border-orange-100">
                <div className="flex items-center gap-6">
                    <Link to="/dashboard" className="flex items-center gap-2 text-slate-500 hover:text-orange-500 transition-colors">
                        <ArrowLeft size={18} />
                        <span className="text-sm font-bold">Dashboard</span>
                    </Link>
                    
                    <div className="h-6 w-px bg-slate-200"></div>

                    <div className="flex items-center gap-2 bg-white/80 border border-slate-200 px-3 py-1.5 rounded-full shadow-sm">
                        <label className="text-[10px] font-black text-slate-400 uppercase tracking-tighter">Model</label>
                        <select 
                            value={selectedModel}
                            onChange={(e) => setSelectedModel(e.target.value)}
                            className="bg-transparent border-none outline-none text-xs font-bold text-orange-600 cursor-pointer min-w-[120px]"
                        >
                            {availableModels.length > 0 ? (
                                availableModels.map(m => (
                                    <option key={m.id} value={m.id}>{m.name}</option>
                                ))
                            ) : (
                                <option value={selectedModel}>{selectedModel}</option>
                            )}
                        </select>
                    </div>
                </div>

                <div className="flex items-center gap-2 italic">
                    <Sparkles className="text-orange-500" size={20} />
                    <span className="font-serif font-black text-xl text-slate-800">DesignStudio <span className="text-orange-500">AI</span></span>
                </div>

                <div className="w-40 flex justify-end">
                     {/* Placeholder for potential profile icon or help */}
                </div>
            </header>

            <main className="flex-1 flex flex-col items-center justify-center p-6 max-w-4xl mx-auto w-full">
                {!isGenerating ? (
                    <div className="w-full space-y-12 animate-fade-in">
                        {/* Welcome Text */}
                        <div className="text-center space-y-4">
                            <h1 className="text-5xl font-serif font-bold text-slate-900 tracking-tight">
                                What shall we <span className="bg-gradient-to-r from-orange-500 to-amber-500 bg-clip-text text-transparent">create</span> today?
                            </h1>
                            <p className="text-slate-500 text-lg">Describe your dream invitation and witness the magic of AI design.</p>
                        </div>

                        {/* Input Area */}
                        <div className="relative group">
                            <div className="absolute -inset-1 bg-gradient-to-r from-orange-400 to-amber-400 rounded-3xl blur opacity-25 group-focus-within:opacity-50 transition duration-1000"></div>
                            <div className="relative bg-white rounded-2xl shadow-xl flex items-center p-2 focus-within:ring-2 ring-orange-200 transition-all">
                                <textarea 
                                    ref={inputRef}
                                    value={prompt}
                                    onChange={(e) => setPrompt(e.target.value)}
                                    placeholder="e.g., A minimalist black tie wedding invitation with gold cursive fonts..."
                                    className="flex-1 bg-transparent border-none outline-none py-4 px-6 text-lg text-slate-700 placeholder:text-slate-300 resize-none h-32 leading-relaxed"
                                    onKeyDown={(e) => {
                                        if (e.key === 'Enter' && !e.shiftKey) {
                                            e.preventDefault();
                                            handleGenerate();
                                        }
                                    }}
                                />
                                <button 
                                    onClick={() => handleGenerate()}
                                    disabled={!prompt.trim()}
                                    className="mb-2 mr-2 p-4 bg-orange-500 hover:bg-orange-600 text-white rounded-xl shadow-lg shadow-orange-500/20 active:scale-95 transition-all disabled:opacity-30 disabled:scale-100"
                                >
                                    <Send size={24} />
                                </button>
                            </div>
                        </div>

                        {/* Suggestions */}
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                            {SUGGESTIONS.map((s, i) => (
                                <button 
                                    key={i}
                                    onClick={() => {
                                        setPrompt(s.prompt);
                                        handleGenerate(s.prompt);
                                    }}
                                    className="p-4 bg-white border border-slate-100 rounded-2xl flex items-center gap-4 text-left hover:border-orange-200 hover:shadow-md transition-all group"
                                >
                                    <div className="p-3 bg-slate-50 rounded-xl group-hover:bg-orange-50 transition-colors">
                                        {s.icon}
                                    </div>
                                    <div>
                                        <div className="font-bold text-slate-700 text-sm">{s.label}</div>
                                        <div className="text-xs text-slate-400 truncate w-48">{s.prompt}</div>
                                    </div>
                                </button>
                            ))}
                        </div>
                    </div>
                ) : (
                    /* Loading State */
                    <div className="flex flex-col items-center justify-center space-y-8 animate-pulse">
                        <div className="relative">
                            <div className="absolute inset-0 bg-orange-500 rounded-full blur-3xl opacity-20 animate-pulse"></div>
                            <div className="w-32 h-32 rounded-full border-4 border-orange-500/20 border-t-orange-500 animate-spin"></div>
                            <Sparkles className="absolute inset-0 m-auto text-orange-500" size={48} />
                        </div>
                        <div className="text-center space-y-2">
                            <h2 className="text-2xl font-serif font-bold text-slate-900">{statusText}</h2>
                            <p className="text-slate-400 text-sm">Our AI is hand-crafting your unique design...</p>
                        </div>
                    </div>
                )}
            </main>

            {/* Footer Background */}
            <div className="fixed bottom-0 left-0 w-full h-32 bg-gradient-to-t from-orange-100/30 to-transparent pointer-events-none"></div>
        </div>
    );
};

export default AiGenerator;
